pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from your version control system
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                
                sh 'npm '
            
            }
        }
        
        stage('Test') {
            steps {
              
                sh 'npm test'
            }
        }
        
        stage('Deploy') {
            steps {
            
                sh 'npm deploy'
            }
        }
    }
}
